version: '3'
services:
  postgres:
    image: postgres
    restart: always
    network_mode: "host"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  mongodb:
    image: mongo
    restart: always
    network_mode: "host"

  python:
    image: python
    restart: always
    network_mode: "host"
    depends_on:
      - postgres
      - mongodb